on:
  push:
    branches:
      - master
      - ghactions
  pull_request:
    branches:
      - master
  # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onschedule
  schedule:
    - cron:  '0 0 * * 1' # every monday at midnight

name: R-CMD-check

jobs:
  # # added so that the workflow doesn't fail.
  # always_runner:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Always run
  #       run: echo "This job is used to prevent the workflow status from showing as failed when all other jobs are skipped"

  R-CMD-check:
    # if: false
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: macOS-latest, r: '4.0'}
        # - { os: macOS-latest, r: 'devel'}
        - { os: windows-latest, r: '4.0'}
        # - { os: ubuntu-18.04, r: '3.4', rspm: "https://packagemanager.rstudio.com/all/__linux__/bionic/latest"}
        # - { os: ubuntu-18.04, r: '3.5', rspm: "https://packagemanager.rstudio.com/all/__linux__/bionic/latest"}
        # - { os: ubuntu-18.04, r: '3.6', rspm: "https://packagemanager.rstudio.com/all/__linux__/bionic/latest"}
        - { os: ubuntu-18.04, r: '4.0', rspm: "https://packagemanager.rstudio.com/all/__linux__/bionic/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        id: install-r
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install pak and query dependencies
        shell: Rscript {0}
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          saveRDS(pak::pkg_deps_tree("local::.", dependencies = TRUE), ".github/r-depends.rds")
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-${{ hashFiles('.github/r-depends.rds') }}
          restore-keys: |
            ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        shell: Rscript {0}
        run: |
          pak::local_system_requirements(execute = TRUE)
      # Use a shorter temp directory for pak installations, due to filename
      # length issues on Windows. https://github.com/r-lib/pak/issues/252
      - name: Windows temp dir
        if: runner.os == 'Windows'
        run: |
          New-Item -Path "C:\" -Name "tmp" -ItemType Directory
          echo "TMPDIR=c:\tmp" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install dependencies
        shell: Rscript {0}
        run: |
          # only install imports, not suggests
          pak::local_install_deps(upgrade = TRUE)
          pak::pkg_install("rcmdcheck")
          pak::pkg_install("sessioninfo")

      - name: Session info
        shell: Rscript {0}
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_: false
        shell: Rscript {0}
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure() # only for previous step
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.config.os }}-r${{ matrix.config.r }}-results
          path: check

      - name: Fix path for Windows caching
        if: runner.os == 'Windows'
        # This is needed because if you use the default tar at this stage,
        # C:/Rtools/bin/tar.exe, it will say that it can't find gzip.exe. So
        # we'll just set the path so that the original tar that would be
        # found, will be found.
        shell: bash
        run: echo "C:/Program Files/Git/usr/bin" >> $GITHUB_PATH
