on:
  push:
    branches:
      - master
      - ghactions
  pull_request:
    branches:
      - master

name: Rituals

jobs:
  # # added so that the workflow doesn't fail.
  # always_runner:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Always run
  #       run: echo "This job is used to prevent the workflow status from showing as failed when all other jobs are skipped"

  Rituals:
    name: Rituals
    # if: false
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: macOS-latest, r: '4.0'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/pr-fetch@master
        name: Git Pull (PR)
        if: github.event_name == 'pull_request'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: r-lib/actions/setup-r@master
        id: install-r
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Git Config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install pak and query dependencies
        shell: Rscript {0}
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          saveRDS(pak::pkg_deps_tree("local::.", dependencies = TRUE), ".github/r-depends.rds")
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-${{ hashFiles('.github/r-depends.rds') }}
          restore-keys: |
            ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        shell: Rscript {0}
        run: |
          pak::local_system_requirements(execute = TRUE)

      - name: Install dependencies
        shell: Rscript {0}
        run: |
          # only install imports, not suggests
          pak::local_install_deps(upgrade = TRUE)

      - name: Document
        run: |
          Rscript -e 'pak::pkg_install("roxygen2")'
          Rscript -e 'roxygen2::roxygenise()'
          git add man/\* NAMESPACE
          git commit -m 'Document (GitHub Actions)' || echo "No documentation changes to commit"

      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: '12.x'
      # - name: Build JS
      #   run: |
      #     yarn install --frozen-lockfile
      #     yarn build
      #     git add inst/assets
      #     git commit -m 'yarn build (GitHub Actions)' || echo "No yarn changes to commit"

      # - name: Code Coverage
      #   run: |
      #     Rscript -e 'pak::pkg_install("covr")'
      #     Rscript -e 'covr::codecov(token = "${{secrets.CODECOV_TOKEN}}")'

      - name: Git Push (PR)
        uses: r-lib/actions/pr-push@master
        if: github.event_name == 'pull_request'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Git Push (MASTER)
        if: github.event_name == 'push'
        run: |
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to push"

      - name: Fix path for Windows caching
        if: runner.os == 'Windows'
        # This is needed because if you use the default tar at this stage,
        # C:/Rtools/bin/tar.exe, it will say that it can't find gzip.exe. So
        # we'll just set the path so that the original tar that would be
        # found, will be found.
        run: echo "::add-path::C:/Program Files/Git/usr/bin"
